### ISSUE TITLE
GXCommon.pas DayOfTheWeek error

### ISSUE THREAD

**Issue by FibonJemer** [Gurux/Gurux.DLMS.Delphi#1]
the code
buff.SetUInt8(System.SysUtils.DayOfWeek(tm) - 1);
buff.SetUInt8(System.SysUtils.DayOfTheWeek(tm));

should be
buff.SetUInt8(System.DateUtils.DayOfWeek(tm) - 1);
buff.SetUInt8(System.DateUtils.DayOfTheWeek(tm));

**Comment by gurux01** [comment]
Hi,

There are two implementations. One for an older version (SysUtils.DayOfWeek) and DateUtils.DayOfWeek for newer versions. Can you describe your problem?

**Comment by FibonJemer** [comment]
Hi, i'm currently using the latest Delphi Community Edition (Tokyo 10.2.3)

I tried to compile the code here and I got the following error
[dcc32 Error] GXCommon.pas(1404): E2003 Undeclared identifier: 'DayOfTheWeek'

**Comment by FibonJemer** [comment]
Thanks. Fixed already on Version 20181030.1
